[app]
name = "demo"
host = "0.0.0.0"
port = "8050"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "12345678"
database = "go_course"

[log]
level = "debug"
path_dir = "logs"
format = "text"
to = "stdout"
